# Generated by Django 2.2 on 2020-03-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMahasiswa', '0003_auto_20200305_1047'),
        ('olahDataJurnalKuliah', '0007_auto_20200311_2052'),
        ('presensiKuliah', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presensi',
            options={'verbose_name': 'presensi', 'verbose_name_plural': 'presensi'},
        ),
        migrations.AddField(
            model_name='presensi',
            name='jurnalPerkuliahan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataJurnalKuliah.detilJurnalKuliah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presensi',
            name='npm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataMahasiswa.mahasiswa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presensi',
            name='presensi',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
