# Generated by Django 2.2 on 2020-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensiKuliah', '0002_auto_20200311_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='jurnalPerkuliahan',
            field=models.CharField(max_length=50),
        ),
    ]
