# Generated by Django 2.2 on 2020-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensiKuliah', '0004_auto_20200311_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='presensi',
            field=models.CharField(max_length=50),
        ),
    ]
