# Generated by Django 2.2 on 2020-03-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataJurnalKuliah', '0007_auto_20200311_2052'),
        ('presensiKuliah', '0005_auto_20200311_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presensi',
            name='jurnal',
        ),
        migrations.AddField(
            model_name='presensi',
            name='jurnalPerkuliahan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olahDataJurnalKuliah.detilJurnalKuliah'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='presensi',
            field=models.BooleanField(default=True),
        ),
    ]
