# Generated by Django 2.2 on 2020-04-01 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presensiKuliah', '0007_auto_20200324_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='importDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presensi',
            name='presenceDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
