# Generated by Django 2.2 on 2020-04-03 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensiKuliah', '0008_auto_20200401_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='nilai',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
