# Generated by Django 2.2 on 2020-04-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensiKuliah', '0009_presensi_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='presenceDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
