# Generated by Django 2.2 on 2020-03-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olahDataMatakuliah', '0010_matakuliah_rumpunmatakuliah'),
        ('olahDataDosen', '0008_auto_20200227_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='jurnalKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahunAjaran', models.IntegerField(verbose_name=[(2019, 2019), (2020, 2020)])),
                ('dosenPengajar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataDosen.dosen')),
                ('mk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataMatakuliah.matakuliah')),
            ],
            options={
                'verbose_name': 'jurnalKuliah',
                'verbose_name_plural': 'jurnalKuliah',
                'ordering': ['-id'],
            },
        ),
    ]
