# Generated by Django 2.2 on 2020-03-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataJurnalKuliah', '0003_auto_20200311_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalkuliah',
            name='semester',
            field=models.CharField(choices=[('Gasal', 'Gasal'), ('Genap', 'Genap')], max_length=5),
        ),
    ]
