# Generated by Django 2.2 on 2020-03-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataJurnalKuliah', '0005_detiljurnalkuliah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detiljurnalkuliah',
            options={'verbose_name': 'detilJurnalKuliah', 'verbose_name_plural': 'detilJurnalKuliah'},
        ),
    ]
