# Generated by Django 2.2 on 2020-03-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataJurnalKuliah', '0006_auto_20200311_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detiljurnalkuliah',
            name='pertemuan',
            field=models.SmallIntegerField(),
        ),
    ]
