# Generated by Django 2.2 on 2020-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataJurnalKuliah', '0007_auto_20200311_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalkuliah',
            name='kelas',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
