# Generated by Django 2.2 on 2020-04-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMahasiswa', '0007_auto_20200327_1341'),
        ('olahDataJurnalKuliah', '0008_jurnalkuliah_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='pesertaKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataJurnalKuliah.jurnalKuliah')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataMahasiswa.mahasiswa')),
            ],
            options={
                'verbose_name': 'pesertaKuliah',
                'verbose_name_plural': 'pesertaKuliah',
            },
        ),
    ]
