# Generated by Django 2.2 on 2020-02-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olahDataMatakuliah', '0003_matakuliah_jmlpertemuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='rps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosenPengampu', models.CharField(choices=[('1', 'as'), ('2', 'as2')], max_length=50)),
                ('capaianPembelajaran', models.TextField()),
                ('prasyarat', models.CharField(max_length=50)),
                ('pathLokasi', models.TextField()),
                ('deskripsi', models.TextField()),
                ('kodemk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataMatakuliah.matakuliah')),
            ],
            options={
                'verbose_name': 'rps',
                'verbose_name_plural': 'rps',
            },
        ),
    ]
