# Generated by Django 2.2 on 2020-02-18 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='dosenPengampu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataDosen.dosen'),
        ),
    ]
