# Generated by Django 2.2 on 2020-02-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0002_auto_20200218_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='prasyarat',
            field=models.TextField(choices=[('SIM3707', 'Data Mining'), ('SIM3201', 'Logika dan Algoritma')]),
        ),
    ]
