# Generated by Django 2.2 on 2020-02-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0003_auto_20200218_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='referensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('utama', 'Utama'), ('pendukung', 'Pendukung')], max_length=15)),
                ('tipe', models.CharField(max_length=10)),
                ('judul', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('tahun', models.SmallIntegerField()),
                ('kota', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'referensi',
                'verbose_name_plural': 'referensi',
            },
        ),
        migrations.CreateModel(
            name='detilRPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kemampuan', models.CharField(max_length=100)),
                ('indikator', models.CharField(max_length=100)),
                ('materi', models.CharField(max_length=100)),
                ('bentukBelajar', models.CharField(max_length=100)),
                ('jenisPenilaian', models.CharField(max_length=50)),
                ('kriteriaPenilaian', models.CharField(max_length=100)),
                ('bobot', models.SmallIntegerField()),
                ('idRps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataRPS.rps')),
                ('idref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olahDataRPS.referensi')),
            ],
            options={
                'verbose_name': 'detilRPS',
                'verbose_name_plural': 'detilRPS',
            },
        ),
    ]
