# Generated by Django 2.2 on 2020-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0004_detilrps_referensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referensi',
            name='tipe',
            field=models.CharField(max_length=30),
        ),
    ]
