# Generated by Django 2.2 on 2020-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0006_auto_20200219_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referensi',
            name='tahun',
            field=models.SmallIntegerField(),
        ),
    ]
