# Generated by Django 2.2 on 2020-02-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0012_auto_20200228_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rps',
            options={'ordering': ['-id'], 'verbose_name': 'rps', 'verbose_name_plural': 'rps'},
        ),
    ]
