# Generated by Django 2.2 on 2020-03-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0013_auto_20200229_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='rps',
            name='capaianPembelajaranProdi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rps',
            name='materiPembelajaran',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rps',
            name='mediaBelajar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rps',
            name='tanggalPenyusunan',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rps',
            name='teamTeaching',
            field=models.TextField(blank=True),
        ),
    ]
