# Generated by Django 2.2 on 2020-03-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0014_auto_20200305_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detilrps',
            old_name='bentukBelajar',
            new_name='bentukMetodeBelajar',
        ),
        migrations.RenameField(
            model_name='detilrps',
            old_name='bobot',
            new_name='bobotPenilaian',
        ),
        migrations.RenameField(
            model_name='detilrps',
            old_name='indikator',
            new_name='indikatorPenilaian',
        ),
        migrations.RenameField(
            model_name='detilrps',
            old_name='jenisPenilaian',
            new_name='teknikPenilaian',
        ),
        migrations.RemoveField(
            model_name='detilrps',
            name='idref',
        ),
        migrations.RemoveField(
            model_name='detilrps',
            name='materi',
        ),
        migrations.AddField(
            model_name='detilrps',
            name='materiBelajar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detilrps',
            name='pengalamanBelajarOffline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detilrps',
            name='pengalamanBelajarOnlineAsinkron',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detilrps',
            name='pengalamanBelajarOnlineSinkron',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rps',
            name='idref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='olahDataRPS.referensi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detilrps',
            name='kemampuan',
            field=models.TextField(blank=True),
        ),
    ]
