# Generated by Django 2.2 on 2020-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0015_auto_20200305_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='tanggalPenyusunan',
            field=models.DateField(),
        ),
    ]
