# Generated by Django 2.2 on 2020-03-09 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0016_auto_20200305_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='idref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olahDataRPS.referensi'),
        ),
    ]
