# Generated by Django 2.2 on 2020-03-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0017_auto_20200309_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='pustaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=30)),
                ('judul', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('tahun', models.SmallIntegerField()),
                ('kota', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'pustaka',
                'verbose_name_plural': 'pustaka',
            },
        ),
    ]
