# Generated by Django 2.2 on 2020-03-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0019_auto_20200309_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='idref',
            field=models.CharField(max_length=10),
        ),
    ]
