# Generated by Django 2.2 on 2020-03-09 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0020_auto_20200309_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='referensi',
            name='refPustaka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='olahDataRPS.pustaka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referensi',
            name='refRps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='olahDataRPS.rps'),
            preserve_default=False,
        ),
    ]
