# Generated by Django 2.2 on 2020-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0021_auto_20200309_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='teamTeaching',
            field=models.TextField(blank=True, null=True),
        ),
    ]
