# Generated by Django 2.2 on 2020-03-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0023_auto_20200310_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referensi',
            name='author',
        ),
        migrations.RemoveField(
            model_name='referensi',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='referensi',
            name='kota',
        ),
        migrations.RemoveField(
            model_name='referensi',
            name='penerbit',
        ),
        migrations.RemoveField(
            model_name='referensi',
            name='tahun',
        ),
        migrations.RemoveField(
            model_name='referensi',
            name='tipe',
        ),
       
    ]
