# Generated by Django 2.2 on 2020-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0025_remove_rps_idref'),
    ]

    operations = [
        migrations.AddField(
            model_name='rps',
            name='rumpun',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
