# Generated by Django 2.2 on 2020-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0026_rps_rumpun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rps',
            name='rumpun',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
