# Generated by Django 2.2 on 2020-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0027_auto_20200314_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='detilrps',
            name='pertemuan',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
