# Generated by Django 2.2 on 2020-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataRPS', '0028_detilrps_pertemuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='referensi',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referensi',
            name='judul',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referensi',
            name='kota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referensi',
            name='penerbit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referensi',
            name='tahun',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referensi',
            name='tipe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
