# Generated by Django 2.2 on 2020-02-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matakuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=30)),
                ('sks', models.IntegerField(max_length=1)),
                ('semester', models.IntegerField(max_length=2)),
            ],
            options={
                'verbose_name': 'matakuliah',
                'verbose_name_plural': 'matakuliah',
            },
        ),
    ]
