# Generated by Django 2.2 on 2020-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMatakuliah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='sks',
            field=models.IntegerField(),
        ),
    ]
