# Generated by Django 2.2 on 2020-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMatakuliah', '0002_auto_20200216_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='jmlPertemuan',
            field=models.SmallIntegerField(default=0),
        ),
    ]
