# Generated by Django 2.2 on 2020-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMatakuliah', '0003_matakuliah_jmlpertemuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Satu'), (2, 'Dua'), (3, 'Tiga'), (4, 'Empat'), (5, 'Lima'), (6, 'Enam'), (7, 'Tujuh'), (8, 'Delapan')]),
        ),
    ]
