# Generated by Django 2.2 on 2020-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMatakuliah', '0004_auto_20200219_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='kode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
