# Generated by Django 2.2 on 2020-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMatakuliah', '0005_auto_20200223_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='kode',
            field=models.CharField(max_length=10),
        ),
    ]
