# Generated by Django 2.2 on 2020-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMatakuliah', '0006_auto_20200223_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='kode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
