# Generated by Django 2.2 on 2020-02-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMatakuliah', '0007_auto_20200225_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'ordering': ['-id'], 'verbose_name': 'matakuliah', 'verbose_name_plural': 'matakuliah'},
        ),
    ]
