# Generated by Django 2.2 on 2020-03-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMatakuliah', '0009_matakuliah_programstudi'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='rumpunMatakuliah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
