# Generated by Django 2.2 on 2020-03-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.userProfiles', unique=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='tahunMasuk',
            field=models.IntegerField(choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)]),
        ),
    ]
