# Generated by Django 2.2 on 2020-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataMahasiswa', '0003_auto_20200305_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
