# Generated by Django 2.2 on 2020-02-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataDosen', '0002_auto_20200221_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.userProfiles'),
        ),
    ]
