# Generated by Django 2.2 on 2020-02-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataDosen', '0005_auto_20200222_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nidn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
