# Generated by Django 2.2 on 2020-02-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olahDataDosen', '0007_auto_20200225_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={'ordering': ['-nik'], 'verbose_name': 'dosen', 'verbose_name_plural': 'dosen'},
        ),
    ]
