# Generated by Django 2.2 on 2020-02-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='jenisKelamin',
            field=models.CharField(choices=[('Laki', 'Laki - Laki'), ('perempuan', 'Perempuan')], max_length=10),
        ),
    ]
