# Generated by Django 2.2 on 2020-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0005_auto_20200220_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='agama',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('katolik', 'Katolik'), ('kristen', 'Kristen'), ('hindu', 'Hindu'), ('budha', 'Budha'), ('konghucu', 'Konghucu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='alamat',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='jenisKelamin',
            field=models.CharField(blank=True, choices=[('Laki', 'Laki - Laki'), ('perempuan', 'Perempuan')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='nama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='noKTP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='tanggalLahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
