# Generated by Django 2.2 on 2020-03-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0008_userprofiles_programstudi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakultas',
            options={'ordering': ['-id'], 'verbose_name': 'fakultas', 'verbose_name_plural': 'fakultas'},
        ),
        migrations.AlterModelOptions(
            name='prodi',
            options={'ordering': ['-id'], 'verbose_name': 'prodi', 'verbose_name_plural': 'prodi'},
        ),
    ]
